# Generated by Django 5.2.4 on 2025-07-29 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(default='no description'),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='tour',
            name='title',
            field=models.CharField(default='no title', max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.CharField(default='no location', max_length=255),
        ),
    ]
